apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogs-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blogs-frontend
  template:
    metadata:
      labels:
        app: blogs-frontend
    spec:
      containers:
      - name: blogs-frontend
        image: chittaranjan27/front-app:latest
        ports:
        - containerPort: 3000

