---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Deploy MySQL Deployment
      community.kubernetes.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        src: "/var/lib/jenkins/workspace/BlogApp/k8s/mysql-deployment.yml"

    - name: Deploy MySQL Service
      community.kubernetes.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        src: "/var/lib/jenkins/workspace/BlogApp/k8s/mysql-service.yml"

    - name: Deploy MySQL PVC
      community.kubernetes.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        src: "/var/lib/jenkins/workspace/BlogApp/k8s/mysql-pvc.yml"

