---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Deploy Frontend Deployment
      community.kubernetes.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        src: "/var/lib/jenkins/workspace/BlogApp/k8s/frontend-deployment.yml"

    - name: Deploy Frontend Service
      community.kubernetes.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        src: "/var/lib/jenkins/workspace/BlogApp/k8s/frontend-service.yml"

